/* Dependency-free 3D dimension viewer. Real cuboid vertices, perspective projection,
   depth-sorted faces, shared physical scale, and pointer/keyboard orbit controls. */
(function(){
  'use strict';
  const presets=[
    {id:'slim',name:'Slim carton',dims:[25,18,10],extra:5,tag:'Brief’s smaller box'},
    {id:'compact',name:'Compact carton',dims:[20,15,10],extra:3,tag:'Demo packing profile'},
    {id:'standard',name:'Standard carton',dims:[30,20,15],extra:0,tag:'Current reference box'}
  ];
  let cleanup=null,refresh=null;
  function html(){return `<section class="card crate-browser" aria-labelledby="crate-title"><div class="card-head"><div><span class="eyebrow">INTERACTIVE CRATE BROWSER</span><h2 id="crate-title">See the space you’re shipping.</h2><p>Compare the boxes at the same scale. Select a carton to calculate its freight.</p></div><span class="crate-tag">3D DIMENSIONS</span></div><div class="crate-layout"><div class="crate-stage-wrap"><div class="crate-toolbar"><div class="crate-legend"><span><i class="crate-current"></i>Current box</span><span><i class="crate-candidate"></i>Selected box</span></div><div class="crate-controls"><button type="button" class="crate-control" data-crate-action="wire" aria-pressed="false">Wireframe</button><button type="button" class="crate-control" data-crate-action="reset">Reset view</button></div></div><div class="crate-stage"><canvas id="crate-canvas" tabindex="0" role="img" aria-label="Interactive 3D comparison of current and selected carton dimensions. Drag or use arrow keys to rotate. Plus and minus zoom. Zero resets the view."></canvas><span class="crate-scale-label">SAME SCALE · EXTERNAL DIMENSIONS</span><div class="crate-zoom"><button type="button" data-crate-action="zoom-in" aria-label="Zoom in">+</button><button type="button" data-crate-action="zoom-out" aria-label="Zoom out">−</button></div></div><div class="crate-stage-foot"><span>Drag to rotate <b>·</b> Scroll to zoom <b>·</b> Arrow keys supported</span><span id="crate-volume" aria-live="polite"></span></div></div><aside class="crate-catalog" aria-label="Carton presets"><div class="crate-catalog-head"><h3>Choose a carton</h3><span>03 DEMO PRESETS</span></div>${presets.map((p,i)=>`<button type="button" class="crate-preset ${i===0?'selected':''}" data-crate-preset="${p.id}" aria-pressed="${i===0}"><span class="crate-preset-line"><strong>${p.name}</strong><span class="crate-selection">${i===0?'✓':''}</span></span><span class="crate-dimensions">${p.dims.join(' × ')} <small>cm</small></span><span class="crate-preset-bottom"><span>${p.tag}</span><span>${(p.dims.reduce((a,b)=>a*b)/1000).toFixed(1)} L</span></span></button>`).join('')}<p class="crate-catalog-note">Fit and protection need a physical check. Presets are illustrative, not certified packaging recommendations.</p></aside></div></section>`;}
  function mount(){destroy();const canvas=document.getElementById('crate-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx){canvas.replaceWith(document.createTextNode('The 3D viewer is unavailable. Use the dimension comparison below.'));return;}const root=canvas.closest('.crate-browser'),form=document.getElementById('pack-form');let yaw=-.58,pitch=.38,zoom=1,wire=false,drag=null,frame=0,w=600,h=330,data=null;
    const rot=v=>{const c=Math.cos(yaw),s=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x=v[0]*c+v[2]*s,z=-v[0]*s+v[2]*c;return[x,v[1]*cp-z*sp,v[1]*sp+z*cp];};
    function read(){const f=form.elements;const a=['length','breadth','height'].map(k=>Number(f['current_'+k].value)),b=['length','breadth','height'].map(k=>Number(f['new_'+k].value));if([...a,...b].some(x=>!Number.isFinite(x)||x<=0||x>300)){data=null;canvas.setAttribute('aria-label','Enter valid dimensions to view the 3D comparison.');document.getElementById('crate-volume').textContent='Enter valid dimensions';schedule();return;}data={a,b};const va=a.reduce((x,y)=>x*y),vb=b.reduce((x,y)=>x*y),change=Math.round((1-vb/va)*100);document.getElementById('crate-volume').textContent=change>=0?change+'% less parcel volume':Math.abs(change)+'% more parcel volume';canvas.setAttribute('aria-label',`3D dimensions. Current carton ${a.join(' by ')} centimeters, ${(va/1000).toFixed(1)} liters. Selected carton ${b.join(' by ')} centimeters, ${(vb/1000).toFixed(1)} liters. Both shown at the same scale. Drag or arrow keys to rotate; plus and minus to zoom.`);let found=false;root.querySelectorAll('[data-crate-preset]').forEach(button=>{const p=presets.find(p=>p.id===button.dataset.cratePreset),selected=p.dims.every((n,i)=>n===b[i]);button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));button.querySelector('.crate-selection').textContent=selected?'✓':'';found=found||selected;});schedule();}
    function schedule(){if(!frame)frame=requestAnimationFrame(()=>{frame=0;draw();});}
    function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);schedule();}
    function draw(){ctx.clearRect(0,0,w,h);if(!data){ctx.fillStyle='#7b8f9d';ctx.font='14px system-ui';ctx.textAlign='center';ctx.fillText('Enter dimensions below to view your cartons.',w/2,h/2);return;}const max=Math.max(...data.a,...data.b),scale=Math.min(w*.25,h*.5)/max*zoom;
      // The backdrop grid is technical reference geometry, not decoration.
      ctx.strokeStyle='#dce5ed';ctx.lineWidth=1;for(let x=18;x<w;x+=28){ctx.beginPath();ctx.moveTo(x,15);ctx.lineTo(x,h-10);ctx.stroke();}for(let y=15;y<h-10;y+=28){ctx.beginPath();ctx.moveTo(10,y);ctx.lineTo(w-10,y);ctx.stroke();}
      drawBox(data.a,w*.26,h*.52,scale,false);drawBox(data.b,w*.75,h*.52,scale,true);
    }
    function drawBox(d,cx,cy,scale,candidate){const [length,breadth,height]=d,x=length/2,y=height/2,z=breadth/2,vertices=[[-x,-y,-z],[x,-y,-z],[x,y,-z],[-x,y,-z],[-x,-y,z],[x,-y,z],[x,y,z],[-x,y,z]],rotated=vertices.map(rot),distance=Math.max(...data.a,...data.b)*7;const project=v=>{const r=rot(v),p=distance/(distance-r[2]);return[cx+r[0]*scale*p,cy-r[1]*scale*p];},points=vertices.map(project);
      ctx.save();ctx.shadowColor='#203d5220';ctx.shadowBlur=18;ctx.fillStyle='#24435f11';ctx.beginPath();ctx.ellipse(cx,cy+Math.max(height,length,breadth)*scale*.54,Math.max(length,breadth)*scale*.47,9*zoom,0,0,Math.PI*2);ctx.fill();ctx.restore();
      const faces=[{ids:[0,1,2,3],shade:0},{ids:[4,7,6,5],shade:1},{ids:[0,4,5,1],shade:2},{ids:[3,2,6,7],shade:3},{ids:[0,3,7,4],shade:4},{ids:[1,5,6,2],shade:5}],palette=candidate?['#73a2ed','#a9cbfa','#235fbd','#c6dfff','#8ab9f3','#6298e2']:['#b39770','#c9af8b','#927657','#e6d3b6','#c0a37c','#a88b65'];faces.sort((a,b)=>a.ids.reduce((n,i)=>n+rotated[i][2],0)-b.ids.reduce((n,i)=>n+rotated[i][2],0));
      for(const face of faces){ctx.beginPath();face.ids.forEach((idx,i)=>i?ctx.lineTo(...points[idx]):ctx.moveTo(...points[idx]));ctx.closePath();if(!wire){ctx.fillStyle=palette[face.shade];ctx.fill();}ctx.strokeStyle=candidate?'#306bc4': '#8a7458';ctx.lineWidth=wire?1.4:1;ctx.stroke();}
      // Center seam denotes the carton fold, and rotates with the model.
      if(!wire){const a=project([0,y,-z]),b=project([0,y,z]);ctx.strokeStyle=candidate?'#2e6fc199':'#967f5c99';ctx.lineWidth=Math.max(2,scale*.6);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();}
      const edges=[{a:vertices[4],b:vertices[5],value:length,axis:'L'},{a:vertices[5],b:vertices[1],value:breadth,axis:'B'},{a:vertices[1],b:vertices[2],value:height,axis:'H'}];
      for(const e of edges){const a=project(e.a),b=project(e.b),dx=b[0]-a[0],dy=b[1]-a[1],norm=Math.hypot(dx,dy)||1,off=e.axis==='H'?14:17,nx=-dy/norm*off,ny=dx/norm*off,aa=[a[0]+nx,a[1]+ny],bb=[b[0]+nx,b[1]+ny];ctx.strokeStyle=candidate?'#245ba5aa':'#79684faa';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(...aa);ctx.lineTo(...bb);ctx.moveTo(aa[0]-nx*.2,aa[1]-ny*.2);ctx.lineTo(aa[0]+nx*.2,aa[1]+ny*.2);ctx.moveTo(bb[0]-nx*.2,bb[1]-ny*.2);ctx.lineTo(bb[0]+nx*.2,bb[1]+ny*.2);ctx.stroke();const tx=(aa[0]+bb[0])/2,ty=(aa[1]+bb[1])/2;const text=e.axis+' '+e.value;ctx.font='600 11px system-ui';const tw=ctx.measureText(text).width;ctx.fillStyle='#f2f6fa';ctx.fillRect(tx-tw/2-4,ty-8,tw+8,16);ctx.fillStyle=candidate?'#245ba5':'#756146';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,tx,ty);}
      ctx.textAlign='center';ctx.fillStyle=candidate?'#145df5':'#746a5a';ctx.font='600 12px system-ui';ctx.fillText(candidate?'SELECTED CARTON':'CURRENT CARTON',cx,h-42);ctx.fillStyle='#657b8c';ctx.font='12px system-ui';ctx.fillText(d.join(' × ')+' cm · '+(length*breadth*height/1000).toFixed(1)+' L',cx,h-23);
    }
    function down(e){if(e.button!==0)return;drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.classList.add('dragging');}
    function move(e){if(!drag)return;yaw+=(e.clientX-drag.x)*.008;pitch=Math.max(-1.2,Math.min(1.2,pitch+(e.clientY-drag.y)*.008));drag={x:e.clientX,y:e.clientY};schedule();}
    function up(){drag=null;canvas.classList.remove('dragging');}
    function wheel(e){e.preventDefault();zoom=Math.max(.55,Math.min(1.65,zoom-e.deltaY*.001));schedule();}
    function key(e){const keys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','0'];if(!keys.includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')yaw-=.12;if(e.key==='ArrowRight')yaw+=.12;if(e.key==='ArrowUp')pitch=Math.max(-1.2,pitch-.12);if(e.key==='ArrowDown')pitch=Math.min(1.2,pitch+.12);if(e.key==='+'||e.key==='=')zoom=Math.min(1.65,zoom+.1);if(e.key==='-')zoom=Math.max(.55,zoom-.1);if(e.key==='0'){yaw=-.58;pitch=.38;zoom=1;}schedule();}
    function click(e){const preset=e.target.closest('[data-crate-preset]'),action=e.target.closest('[data-crate-action]');if(preset){const p=presets.find(x=>x.id===preset.dataset.cratePreset);['length','breadth','height'].forEach((k,i)=>form.elements['new_'+k].value=p.dims[i]);form.elements.extra.value=p.extra;form.dispatchEvent(new Event('input',{bubbles:true}));read();}if(action){if(action.dataset.crateAction==='reset'){yaw=-.58;pitch=.38;zoom=1;}if(action.dataset.crateAction==='wire'){wire=!wire;action.setAttribute('aria-pressed',String(wire));}if(action.dataset.crateAction==='zoom-in')zoom=Math.min(1.65,zoom+.1);if(action.dataset.crateAction==='zoom-out')zoom=Math.max(.55,zoom-.1);schedule();}}
    canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('lostpointercapture',up);canvas.addEventListener('wheel',wheel,{passive:false});canvas.addEventListener('keydown',key);root.addEventListener('click',click);const observer=new ResizeObserver(resize);observer.observe(canvas);refresh=read;read();resize();cleanup=()=>{observer.disconnect();cancelAnimationFrame(frame);root.removeEventListener('click',click);refresh=null;};
  }
  function destroy(){if(cleanup){cleanup();cleanup=null;}}
  function update(){if(refresh)refresh();}
  window.NovaCrates={html,mount,destroy,update};
})();
