(function(){
 'use strict';
 const button=document.createElement('button');button.className='watch-demo';button.type='button';button.dataset.action='watch-video';button.innerHTML='<span class="play-symbol" aria-hidden="true">▶</span> Watch demo';document.querySelector('.top-actions').prepend(button);
 const dialog=document.createElement('dialog');dialog.className='film-dialog';dialog.id='film-dialog';dialog.setAttribute('aria-labelledby','film-title');dialog.innerHTML='<div class="dialog-head"><div><span class="eyebrow">NOVACORE · PRODUCT WALKTHROUGH</span><h2 id="film-title">From packed parcel to proven margin.</h2></div><button class="icon-button" data-close aria-label="Close video">×</button></div><video controls playsinline preload="none" poster="./media/demo-poster.jpg" aria-label="NOVACORE product demo with chapter captions and music"><source src="./media/novacore-demo.mp4" type="video/mp4"><track kind="captions" src="./media/demo-captions.vtt" srclang="en" label="English">Your browser cannot play this video. Download the MP4 below.</video><div class="film-video-footer"><p>Real MVP interactions, chapter captions, and an original soundtrack. Sample shipments, rate cards, and recorded credit outcomes are illustrative.</p><div class="film-video-links"><a href="./media/novacore-demo.mp4" download>Download MP4</a><a href="./media/demo-transcript.txt" target="_blank" rel="noopener">Read transcript</a></div></div>';document.body.append(dialog);
 function watch(){dialog.showModal();const video=dialog.querySelector('video');video.play().catch(()=>{});}
 document.addEventListener('click',e=>{if(e.target.closest('[data-action="watch-video"]'))watch();});dialog.addEventListener('close',()=>dialog.querySelector('video').pause());dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
 const invitation='<section class="pitch-video-invite"><button class="pitch-video-play" type="button" data-action="watch-video" aria-label="Play product demo">▶</button><div><h3>Watch the product in action.</h3><p>A short walkthrough of measurement, reconciliation, recovery, and the 3D crate browser.</p></div><button type="button" class="button secondary small" data-action="watch-video">Watch demo</button></section>';
 const originalPitch=pitch;pitch=function(){return originalPitch().replace('<section class="pitch-banner">',invitation+'<section class="pitch-banner">');};if(view==='pitch')render();
})();
