/* Shared, deterministic freight rules. Money is computed in integer paise. */
(function(root){
  'use strict';
  const DEFAULT_CONTRACT={version:'DEMO-2026.10-v1',courier:'Demo Express',service:'Surface · national',divisor:5000,minimum:0.5,slab:0.5,basePaise:6000,stepPaise:2000,surchargePaise:0};
  function number(value,label,min=0,max=100000){const n=Number(value);if(!Number.isFinite(n)||n<min||n>max)throw new Error(`${label} must be between ${min} and ${max}.`);return n;}
  function contract(c){number(c.divisor,'Divisor',1,100000);number(c.minimum,'Minimum weight',0.01,100);number(c.slab,'Slab increment',0.01,100);for(const k of ['basePaise','stepPaise','surchargePaise']){number(c[k],k,0,100000000);if(!Number.isInteger(c[k]))throw new Error('Rates must use whole paise.');}if(!String(c.version||'').trim())throw new Error('Give the rate card a version.');return c;}
  function price(m,c=DEFAULT_CONTRACT){contract(c);const actual=number(m.weight,'Packed weight',0.001,1000);const l=number(m.length,'Length',0.1,300),b=number(m.breadth,'Breadth',0.1,300),h=number(m.height,'Height',0.1,300);const volumetric=l*b*h/c.divisor;const chargeable=Math.max(actual,volumetric);const steps=Math.max(0,Math.ceil((chargeable-c.minimum-1e-9)/c.slab));const billable=Math.round((c.minimum+steps*c.slab)*1e6)/1e6;return{actual,volumetric,chargeable,billable,expectedPaise:c.basePaise+steps*c.stepPaise+c.surchargePaise,steps};}
  function flags(m,c=DEFAULT_CONTRACT,profile){const p=price(m,c),out=[];if(profile&&['length','breadth','height'].some(k=>Math.abs(Number(m[k])-Number(profile[k]))>2))out.push('Dimensions differ from the packaging profile by more than 2 cm.');if(profile&&Math.abs(Number(m.weight)-profile.weight)>Math.max(.15,profile.weight*.25))out.push('Packed weight differs from the SKU reference.');const next=c.minimum+Math.max(0,Math.ceil((p.chargeable-c.minimum-1e-9)/c.slab))*c.slab;if(next-p.chargeable>=0&&next-p.chargeable<=.05)out.push('Within 50 g of a billing boundary. Re-measure before dispatch.');return out;}
  function parseCSV(text){text=String(text).replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(quoted){quoted=false;}else if(cell===''){quoted=true;}else throw new Error('Unexpected quote in CSV.');}else if(ch===','&&!quoted){row.push(cell.trim());cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=ch;}if(quoted)throw new Error('CSV has an unclosed quote.');row.push(cell.trim());if(row.some(Boolean))rows.push(row);if(rows.length<2)throw new Error('Add a header and at least one invoice row.');const headers=rows.shift().map(x=>x.toLowerCase());if(new Set(headers).size!==headers.length)throw new Error('CSV has duplicate headers.');const required=['awb','billed_weight_kg','billed_amount'];for(const key of required)if(!headers.includes(key))throw new Error(`Missing CSV column: ${key}.`);return rows.map((r,i)=>{if(r.length!==headers.length)throw new Error(`Row ${i+2} has an incorrect number of columns.`);const o=Object.fromEntries(headers.map((h,j)=>[h,r[j]]));if(!o.awb)throw new Error(`Row ${i+2}: shipment number is missing.`);number(o.billed_weight_kg,'Billed weight',.001,1000);number(o.billed_amount,'Billed amount',0,1000000);if(!/^\d+(\.\d{1,2})?$/.test(o.billed_amount))throw new Error(`Row ${i+2}: amount must have at most two decimals.`);const [whole,decimal='']=o.billed_amount.split('.');return{awb:o.awb,billedWeight:Number(o.billed_weight_kg),billedPaise:Number(whole)*100+Number(decimal.padEnd(2,'0')),invoice:o.invoice_id||'Imported invoice'};});}
  const api={DEFAULT_CONTRACT,price,flags,parseCSV,validateContract:contract};root.NovaEngine=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
